### ISSUE TITLE
"Error while starting Solidworks" in Cura 3.2

### ISSUE THREAD

**Issue by poolec4** [thopiekar/CuraSolidWorksPlugin#48]
![image](https://user-images.githubusercontent.com/12722146/36064731-ffe0c028-0e5c-11e8-86d4-57fbcdc67e20.png)
When attempting to import a Solidworks part file, Cura is unable to start the program. Here are the steps I have taken so far:

- Removed and reinstalled the plugin
- Ended all Solidworks processes
- Restarted computer

Here are (the important parts) of the log file:

[cura.log](https://github.com/thopiekar/CuraSolidWorksPlugin/files/1713599/cura.log)

**Comment by thopiekar** [comment]
Could be a known problem. As far as I know Ultimaker has not updated the plugin for a long time. Since the last upload there have been many versions already.

If you don't mind using an unreleased version (with many additions), you can download and install this plugin package manually:
http://thopiekar.eu/download/CuraSolidWorksPlugin-0.5.0.curaplugin

If you need additional instructions how to do that, just ask. Also I would love to hear whether your problem is fixed using the new version or not.

Regards!

**Comment by poolec4** [comment]
I installed version 0.5 manually, but now I receive a new error. It says that the file is invalid (I tried several different part files). I have verified that the plugin recognizes and has access to all of the Solidworks functions in the new configuration window.
![image](https://user-images.githubusercontent.com/12722146/36082303-43bd1476-0f76-11e8-9009-69de0e40ddfc.png)

Here is the log output:
[cura.log](https://github.com/thopiekar/CuraSolidWorksPlugin/files/1715195/cura.log)

Thanks for your help

**Comment by thopiekar** [comment]
Could you please open the file called:
C:\Users\Chris\AppData\Roaming\cura\3.2\plugins\CuraSolidWorksPlugin\CuraSolidWorksPlugin\CadIntegrationUtils\SystemUtils.py
Replace in line 10:
`raise ValueError("Bad path passed!")`
with:
`raise ValueError("Bad path passed: {}".format(dosPath))`
and send a log again?

Thanks!

**Comment by poolec4** [comment]
Here's the log after changing that line:
[cura.log](https://github.com/thopiekar/CuraSolidWorksPlugin/files/1716766/cura.log)

**Comment by thopiekar** [comment]
Thanks!
Now another one. Please add:
`        Logger.log("d", "Queried Windows registry: {}". format(sldwks_exe))`
into SolidWorksReader.py between line 142 and 143, so the whole function looks like:
```
    def getSoftwareInstallPath(self, major_version):
        executable_extension = ".exe"
        regpath = "{}\shell\open\command".format(self.getVersionedServiceName(major_version))
        sldwks_exe = winreg.QueryValue(winreg.HKEY_CLASSES_ROOT, regpath)
        Logger.log("d", "Queried Windows registry: {}". format(repr(sldwks_exe)))
        sldwks_exe = sldwks_exe[:sldwks_exe.find(executable_extension)+len(executable_extension)+1]
        sldwks_exe = convertDosPathIntoLongPath(sldwks_exe)
        sldwkd_inst = os.path.split(sldwks_exe)[0]
        return sldwkd_inst
```

I need to know the content of sldwks_exe. The function we debugged before depends on it.

**Comment by poolec4** [comment]
Here's the ouput:
`2018-02-12 12:08:47,315 - DEBUG - [(22008)-MainThread] CuraSolidWorksPlugin.SolidWorksReader.getSoftwareInstallPath [143]: Queried Windows registry: D:\Program Files\SOLIDWORKS\SLDWORKS.exe "%1"`

Could it be that I have Solidworks installed on a different drive than Cura?

Here's the full log again:

[cura.log](https://github.com/thopiekar/CuraSolidWorksPlugin/files/1717120/cura.log)

**Comment by thopiekar** [comment]
Hahah, you send me probably the old log before, right? ^^'
I thought that I have issues with my eyes..

Hmm, the problem is that your path is not shortened.. It should be no issue that you installed it on D. Something else is going terribly wrong.. however I'm able to reproduce it. Thank you!

![image](https://user-images.githubusercontent.com/1847437/36109828-cec9f7e6-1020-11e8-8238-ca2cb0133206.png)

**Comment by thopiekar** [comment]
Hmm, couldn't find a solution for this, but rewrote the part, which is failing. The current function does not return any errors, but returns "Nothing", when something went wrong.
Please replace the content of SystemUtils.py with:

```
# Copyright (c) 2017 Thomas Karl Pietrowski

import win32api

def convertDosPathIntoLongPath(dosPath):
    buffer = win32api.GetLongPathName(dosPath)
    return buffer
```

If there are errors, then it should return which one it is.

But I'm myself still getting an error:
```
Traceback (most recent call last):
  File "C:\Users\Thomas Pietrowski\AppData\Roaming\cura\3.2\plugins\CuraSolidWorksPlugin\CuraSolidWorksPlugin\tests\test_find_installation_path.py", line 12, in <module>
    sldwks_exe = convertDosPathIntoLongPath(sldwks_exe)
  File "C:\Users\Thomas Pietrowski\AppData\Roaming\cura\3.2\plugins\CuraSolidWorksPlugin\CuraSolidWorksPlugin\SystemUtils.py", line 6, in convertDosPathIntoLongPath
    buffer = win32api.GetLongPathName(dosPath)
pywintypes.error: (21, 'GetLongPathNameW', 'Das Gerät ist nicht bereit.')
```

Could you verify, whether `D:\Program Files\SOLIDWORKS\SLDWORKS.exe` or `D:\Program Files\SOLIDWORKS\` really exists?

**Comment by poolec4** [comment]
I made the change to SystemUtils.py and noticed this in the log:
`ImportError: No module named 'win32api'`

I have verified that `D:\Program Files\SOLIDWORKS\SLDWORKS.exe` exists and does open Solidworks successfully.

[cura.log](https://github.com/thopiekar/CuraSolidWorksPlugin/files/1717339/cura.log)

**Comment by thopiekar** [comment]
The `ImportError: No module named 'win32api'` error is normal. It is checking, whether a module is installed in Cura or not. I'm still waiting for Ultimaker to get it included.

I checked the log and it still mentions:
```
2018-02-12 13:25:40,905 - ERROR - [(1528)-Thread-5] UM.Logger.logException [86]:   File "C:\Users\Chris\AppData\Roaming\cura\3.2\plugins\CuraSolidWorksPlugin\CuraSolidWorksPlugin\CadIntegrationUtils\SystemUtils.py", line 10, in convertDosPathIntoLongPath
2018-02-12 13:25:40,906 - ERROR - [(1528)-Thread-5] UM.Logger.logException [86]:     raise ValueError("Bad path passed: {}".format(dosPath))
2018-02-12 13:25:40,908 - ERROR - [(1528)-Thread-5] UM.Logger.logException [86]: ValueError: Bad path passed: None
```

Does not seem that you changed the file correctly, because the line `raise ValueError("Bad path passed: {}".format(dosPath))` does not appear anymore (see: https://github.com/thopiekar/CuraSolidWorksPlugin/issues/48#issuecomment-364999394).

**Comment by poolec4** [comment]
You're right, my apologies - I must have copied the file without saving the changes.
Now there is this:

`2018-02-12 17:28:50,621 - ERROR - [(4448)-Thread-5] UM.Logger.logException [86]:     buffer = win32api.GetLongPathName(dosPath)
2018-02-12 17:28:50,622 - ERROR - [(4448)-Thread-5] UM.Logger.logException [86]: TypeError: None is not a valid string in this context`

[cura.log](https://github.com/thopiekar/CuraSolidWorksPlugin/files/1717937/cura.log)

**Comment by thopiekar** [comment]
Good morning!

let's continue to debug your problem. The log says that there is something wrong when `tempdir` is passed to:
```
2018-02-12 17:28:50,702 - ERROR - [(4448)-Thread-5] UM.Logger.logException [86]:   File "C:\Users\Chris\AppData\Roaming\cura\3.2\plugins\CuraSolidWorksPlugin\CuraSolidWorksPlugin\CadIntegrationUtils\CommonReader.py", line 158, in readOnSingleAppLayer
2018-02-12 17:28:50,703 - ERROR - [(4448)-Thread-5] UM.Logger.logException [86]:     tempdir = convertDosPathIntoLongPath(tempdir)
```

Could you add before this line another debug print?
`Logger.log("d", "TEMPDIR: {}". format(tempdir))`

Thanks!

**Comment by thopiekar** [comment]
@poolec4 Please test: https://thopiekar.eu/download/CuraSolidWorksPlugin-0.5.1.curaplugin

**Comment by poolec4** [comment]
I have installed 0.5.1. I receive the same error, but here is the output of the log you added:

`2018-02-13 19:00:19,748 - DEBUG - [(9568)-Thread-5] CuraSolidWorksPlugin.CadIntegrationUtils.CommonReader.readOnSingleAppLayer [157]: Using suggested tempdir: 'C:\\Users\\Chris\\AppData\\Local\\Temp'`

[Here's the full log](https://github.com/thopiekar/CuraSolidWorksPlugin/files/1722165/cura.log)

**Comment by thopiekar** [comment]
The log looks promising to understand what's going on. The issue is kind of the same, but now at a different place. It happens because the plugin is using 3MF I guess. I was never able to practically Test ist because I only had access to SolidWorks 2016, which has no 3MF support.

**Comment by thopiekar** [comment]
https://thopiekar.eu/download/CuraSolidWorksPlugin-0.5.2.curaplugin

**Comment by thopiekar** [comment]
@poolec4 Any news?

**Comment by poolec4** [comment]
Hey, sorry for the delay.

I'm still having issues with v0.5.2. Here's the new log: 
[cura.log](https://github.com/thopiekar/CuraSolidWorksPlugin/files/1734285/cura.log)

**Comment by thopiekar** [comment]
Hey, yesterday I just released a new version of the plugin. With the help of someone from the SolidWorks group on Facebook I was able to get a 3mf file of the test model I have and could reproduce the issues. 

https://community.ultimaker.com/topic/19898-3ds-solidworks-plugin-053/

However, I could not practically test it with SolidWorks 2017, but using the test files and the debug mode I programmed, I hope I came closer.

Regards

**Comment by poolec4** [comment]
Awesome! The plugin works again with SW 2017 and Cura 3.2.1

Thank you so much for your help and for creating a great plugin!

**Comment by thopiekar** [comment]
Many many thanks for taking your time!

There is one wish left from my side. Could you please test the plugin using all filetypes?
There are example files at:
https://github.com/thopiekar/CuraSolidWorksPlugin/tree/master/tests/SolidWorks%20files
Each is, as you notice, for a part, assembly and drawing.

Thanks again and hope you had and still have a great weekend!

**Comment by poolec4** [comment]
Just tested all three filetypes and they all work perfectly. Thanks again!

**Comment by thopiekar** [comment]
@poolec4 I noticed you were also involved in the past to the Ultimaker community thread. Would be great to see you there again!
- https://community.ultimaker.com/topic/19898-3ds-solidworks-plugin-054/
